-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Account CASCADE;
DROP TABLE IF EXISTS Chore CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS Sub_category CASCADE;